name: Package request
about: Suggest an idea for this project
title: '[Package Request] Software Name'
labels: enhancement
assignees: ''

  - type: textarea
    attributes:
      label: Software Info
      description: Tell us something about the software you want the package for
      value: |
        - Name:
        - Short Description:
        - Software Site:
        - Software Sorce Url [If exists]:
        - Current Latest Version:
        - Dependencies:
        - Additional Info:
