name: CI/CD

on: push

jobs:
  verify-packages:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Add New Package Source
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: source add --name='repo' --source='./nupkgs/' --priority='1'
      - name: Install Packages
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: install onefetch tree-sitter dcforoffice blitz.gg leagueoflegendseune action -dvy
      - name: Uninstall Packages
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: uninstall onefetch tree-sitter dcforoffice blitz.gg leagueoflegendseune action -dvy
