name: CI

on:
  push:
    paths-ignore:
      - README.md

jobs:
  test:
    uses: kamack38/chocopkgs/.github/workflows/_test-package.yml@master
    with:
      packages: >-
        [
          "7tt",
          "action",
          "betterdiscord",
          "blitz.gg",
          "betterdiscord",
          "borderlessminecraft",
          "dcforoffice",
          "jarfix",
          "leagueoflegendseune",
          "nvm.install",
          "nvm.portable",
          "onefetch",
          "portmaster",
          "tree-sitter",
          ]
