name: CI/CD

on:
  push:
    paths:
      - '**/leagueoflegendseune**'
      - '**/workflows/test-leagueoflegendseune.yml'

jobs:
  test-leagueoflegendseune:
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Add New Package Source
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: source add --name='repo' --source='./nupkgs/' --priority='1'
      - name: Install League Of Legends
        uses: crazy-max/ghaction-chocolatey@v1
        timeout-minutes: 2
        with:
          args: install leagueoflegendseune -dvy
      - name: Uninstall League Of Legends
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: uninstall leagueoflegendseune -dvy
