name: CI/CD

on:
  push:
    paths:
      - '**/7tt**'
      - '**/workflows/test-7tt.yml'

jobs:
  test-7tt:
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Add New Package Source
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: source add --name='repo' --source='./nupkgs/' --priority='1'
      - name: Install 7+ Taskbar Tweaker
        uses: crazy-max/ghaction-chocolatey@v1
        timeout-minutes: 2
        with:
          args: install 7tt -dvy
      - name: Uninstall 7+ Taskbar Tweaker
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: uninstall 7tt -dvy
