name: CI/CD

on:
  push:
    paths:
      - '**/betterdiscord**'
      - '**/workflows/test-betterdiscord.yml'

jobs:
  test-betterdiscord:
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Add New Package Source
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: source add --name='repo' --source='./nupkgs/' --priority='1'
      - name: Install BetterDiscord
        uses: crazy-max/ghaction-chocolatey@v1
        timeout-minutes: 3
        with:
          args: install betterdiscord -dvy
      - name: Uninstall BetterDiscord
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: uninstall betterdiscord -dvy
