name: Package Update

# on: schedule:
#   - time: '30 18 * * *'

on: push

jobs:
  update-packages:
    runs-on: windows-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2.3.4
      -
        name: Install & Import AU
        shell: powershell
        run: |
           Install-Module au
           Import-Module au
      -
        name: Run script
        shell: powershell
        run: |
          .\update_all.ps1