name: Package Update

on: 
  schedule:
    - cron: '30 18 * * *'
  workflow_call:

jobs:
  update-packages:
    runs-on: windows-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2.3.4
      -
        name: Install & Import AU
        shell: powershell
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module au
          Import-Module au
      -
        name: Run script
        shell: powershell
        run: |
          .\update_all.ps1